---

.script-git-submodule: &script-git-submodule
  - |
    git submodule sync --recursive
    git submodule update --init --recursive

.script-bootstrap-packer: &script-bootstrap-packer
  - |
    if ! [[ -x "$(command -v packer)" ]]; then
      curl -skL -O https://releases.hashicorp.com/packer/1.6.6/packer_1.6.6_linux_amd64.zip
      sudo unzip -qq -o -d /usr/local/bin packer_1.6.6_linux_amd64.zip
      rm -rf packer_1.6.6_linux_amd64.zip
    fi

.script-bootstrap-docker: &script-bootstrap-docker
  - |
    if ! [[ -x "$(command -v docker)" ]]; then
      curl -skL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      sudo apt-get update
      sudo apt-get -y install containerd.io docker-ce docker-ce-cli
    fi
    sudo systemctl start docker.service
    echo $DOCKER_HUB_TOKEN | docker login --username=$DOCKER_HUB_USERNAME --password-stdin

.script-bootstrap-ansible: &script-bootstrap-ansible
  - |
    if ! [[ -x "$(command -v ansible)" ]]; then
      sudo apt-get update
      sudo apt-get -y install ca-certificates curl gcc iproute2 pwgen python3 python3-dev sudo
      curl -skL https://bootstrap.pypa.io/get-pip.py | sudo -H python3 - --prefix=/usr/local
      sudo -H pip3 install --prefix=/usr/local --upgrade --requirement requirements.txt
    fi

.script-linters: &script-linters
  - |
    yamllint .
    ansible-lint
    flake8

.script-packer-build: &script-packer-build
  - |
    cd $CI_PROJECT_DIR/packer/$_PACKER_BUILDER_PROVIDER-$_PACKER_BUILDER_VERSION
    export _ORG=$CI_PROJECT_NAMESPACE
    export _IMAGE=$(echo $CI_PROJECT_NAME | sed 's/^docker-//g')-$_PACKER_BUILDER_VERSION
    packer build packer.json
    export _ID=$(docker images | awk '{print $3}' | awk 'NR==2')
    mkdir -p output-docker
    docker tag $_ID $_ORG/$_IMAGE:latest
    docker save $_ORG/$_IMAGE:latest | gzip -9 > output-docker/image.tar.gz

.script-docker-push: &script-docker-push
  - |
    cd $CI_PROJECT_DIR/packer/$_PACKER_BUILDER_PROVIDER-$_PACKER_BUILDER_VERSION
    export _ORG=$CI_PROJECT_NAMESPACE
    export _IMAGE=$(echo $CI_PROJECT_NAME | sed 's/^docker-//g')-$_PACKER_BUILDER_VERSION
    if [[ -n "$CI_COMMIT_TAG" ]] && [[ "$CI_COMMIT_TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]]; then
      export _TAG=$CI_COMMIT_TAG
    elif [[ -n "$CI_COMMIT_BRANCH" ]] && [[ "$CI_COMMIT_BRANCH" =~ master ]]; then
      export _TAG=$(date +%Y%m%d).0.0
    else
      exit 0
    fi
    docker load --input output-docker/image.tar.gz
    docker push $_ORG/$_IMAGE:latest
    docker tag $_ORG/$_IMAGE:latest $_ORG/$_IMAGE:$_TAG
    docker push $_ORG/$_IMAGE:$_TAG

.job-packer-build: &job-packer-build
  script:
    - *script-bootstrap-packer
    - *script-bootstrap-docker
    - *script-bootstrap-ansible
    - *script-linters
    - *script-packer-build

.job-docker-push: &job-docker-push
  script:
    - *script-bootstrap-docker
    - *script-docker-push

default:
  retry: 2
  before_script:
    - *script-git-submodule

build:docker-7.2:
  <<: *job-packer-build
  stage: build
  cache:
    key: "$CI_PIPELINE_ID-docker-7.2"
    paths:
      - packer/*/output-docker/*.tar.gz
  variables:
    _PACKER_BUILDER_PROVIDER: "docker"
    _PACKER_BUILDER_VERSION: "7.2"

deploy:docker-7.2:
  <<: *job-docker-push
  stage: deploy
  cache:
    key: "$CI_PIPELINE_ID-docker-7.2"
    paths:
      - packer/*/output-docker/*.tar.gz
    policy: pull
  variables:
    _PACKER_BUILDER_PROVIDER: "docker"
    _PACKER_BUILDER_VERSION: "7.2"
  needs:
    - build:docker-7.2

build:docker-7.1:
  <<: *job-packer-build
  stage: build
  cache:
    key: "$CI_PIPELINE_ID-docker-7.1"
    paths:
      - packer/*/output-docker/*.tar.gz
  variables:
    _PACKER_BUILDER_PROVIDER: "docker"
    _PACKER_BUILDER_VERSION: "7.1"

deploy:docker-7.1:
  <<: *job-docker-push
  stage: deploy
  cache:
    key: "$CI_PIPELINE_ID-docker-7.1"
    paths:
      - packer/*/output-docker/*.tar.gz
    policy: pull
  variables:
    _PACKER_BUILDER_PROVIDER: "docker"
    _PACKER_BUILDER_VERSION: "7.1"
  needs:
    - build:docker-7.1
