---

.script-git-submodule: &script-git-submodule
  - |
    git submodule sync --recursive
    git submodule update --init --recursive

.script-bootstrap-packer: &script-bootstrap-packer
  - |
    curl -skL -O https://github.com/hashicorp/packer/releases/download/nightly/packer_linux_amd64.zip
    sudo unzip -qq -o -d /usr/local/bin packer_linux_amd64.zip
    rm -rf packer_linux_amd64.zip

.script-bootstrap-docker: &script-bootstrap-docker
  - |
    curl -skL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    sudo apt-get update
    sudo apt-get -y install containerd.io docker-ce docker-ce-cli
    sudo systemctl start docker.service

.script-bootstrap-ansible: &script-bootstrap-ansible
  - |
    sudo apt-get update
    sudo apt-get -y install ca-certificates curl gcc iproute2 pwgen python3 python3-dev sudo
    curl -skL https://bootstrap.pypa.io/get-pip.py | sudo -H python3 - --prefix=/usr/local
    sudo -H pip3 install --prefix=/usr/local --upgrade --ignore-installed --requirement requirements.txt

.script-linters: &script-linters
  - |
    yamllint .
    ansible-lint
    flake8

.script-packer-build: &script-packer-build
  - |
    cd packer/$_PACKER_BUILDER_PROVIDER-$_PACKER_BUILDER_VERSION
    sudo packer build packer.json

.script-docker-push: &script-docker-push
  - |
    echo $DOCKER_TOKEN | sudo docker login --username=$DOCKER_USERNAME --password-stdin
    export _DOCKER_IMAGE=$(sudo docker images | awk '{print $3}' | awk 'NR==2')
    export _DOCKER_REPO=$CI_PROJECT_NAMESPACE/$(echo $CI_PROJECT_NAME | sed 's/^docker-//g')
    if [[ -n "$CI_COMMIT_TAG" ]] && [[ "$CI_COMMIT_TAG" =~ ^$PACKER_BUILDER_VERSION ]]; then
      sudo docker tag $_DOCKER_IMAGE $_DOCKER_REPO:$CI_COMMIT_TAG
      sudo docker push $_DOCKER_REPO:$CI_COMMIT_TAG
      sudo docker tag $_DOCKER_IMAGE $_DOCKER_REPO:latest
      sudo docker push $_DOCKER_REPO:latest
    elif [[ -n "$CI_COMMIT_BRANCH" ]] && [[ "$CI_COMMIT_BRANCH" =~ master ]]; then
      sudo docker tag $_DOCKER_IMAGE $_DOCKER_REPO:$_PACKER_BUILDER_VERSION
      sudo docker push $_DOCKER_REPO:$_PACKER_BUILDER_VERSION
    fi

.job-packer: &job-packer
  script:
    - *script-bootstrap-packer
    - *script-bootstrap-docker
    - *script-bootstrap-ansible
    - *script-linters
    - *script-packer-build
    - *script-docker-push

default:
  before_script:
    - *script-git-submodule

docker-7.1:
  <<: *job-packer
  variables:
    _PACKER_BUILDER_PROVIDER: "docker"
    _PACKER_BUILDER_VERSION: "7.1"

docker-7.2:
  <<: *job-packer
  variables:
    _PACKER_BUILDER_PROVIDER: "docker"
    _PACKER_BUILDER_VERSION: "7.2"
