---

.script-git-submodule: &script-git-submodule
  - |
    git submodule sync --recursive
    git submodule update --init --recursive

.script-linters: &script-linters
  - |
    flake8
    yamllint .
    ansible-lint

.script-bootstrap-python: &script-bootstrap-python
  - |
    if ! [[ -x "$(command -v pipx)" && -x "$(command -v flake8)" && -x "$(command -v yamllint)" ]]; then
      export DEBIAN_FRONTEND="noninteractive"
      printf "Components:\nEnabled: yes\nX-Repolib-Name: alvistack\nSigned-By: /etc/apt/keyrings/home-alvistack.asc\nSuites: /\nTypes: deb\nURIs: http://downloadcontent.opensuse.org/repositories/home:/alvistack/xUbuntu_24.04\n" | sudo tee /etc/apt/sources.list.d/home-alvistack.sources > /dev/null
      curl -fsSL https://downloadcontent.opensuse.org/repositories/home:alvistack/xUbuntu_24.04/Release.key | sudo tee /etc/apt/keyrings/home-alvistack.asc > /dev/null
      sudo -E apt-get update
      sudo -E apt-get install -y bzip2 ca-certificates curl flake8 gcc gnupg gzip iproute2 pipx procps python3 python3-apt python3-cryptography python3-flake8 python3-jmespath python3-lxml python3-netaddr python3-pip python3-setuptools python3-venv python3-virtualenv python3-wheel sudo tar unzip xz-utils yamllint zip
    fi
    sh -x -c "python3 --version"
    sh -x -c "pipx --version"
    sh -x -c "flake8 --version"
    sh -x -c "yamllint --version"

.script-bootstrap-ansible: &script-bootstrap-ansible
  - |
    if ! [[ -x "$(command -v ansible)" && -x "$(command -v ansible-lint)" ]]; then
      export DEBIAN_FRONTEND="noninteractive"
      printf "Components:\nEnabled: yes\nX-Repolib-Name: alvistack\nSigned-By: /etc/apt/keyrings/home-alvistack.asc\nSuites: /\nTypes: deb\nURIs: http://downloadcontent.opensuse.org/repositories/home:/alvistack/xUbuntu_24.04\n" | sudo tee /etc/apt/sources.list.d/home-alvistack.sources > /dev/null
      curl -fsSL https://downloadcontent.opensuse.org/repositories/home:alvistack/xUbuntu_24.04/Release.key | sudo tee /etc/apt/keyrings/home-alvistack.asc > /dev/null
      sudo -E apt-get update
      sudo -E apt-get install -y ansible ansible-lint python3-docker python3-netaddr python3-vagrant
    fi
    sh -x -c "ansible --version"
    sh -x -c "ansible-lint --version"

.script-bootstrap-molecule: &script-bootstrap-molecule
  - |
    if ! [[ -x "$(command -v molecule)" ]]; then
      export DEBIAN_FRONTEND="noninteractive"
      printf "Components:\nEnabled: yes\nX-Repolib-Name: alvistack\nSigned-By: /etc/apt/keyrings/home-alvistack.asc\nSuites: /\nTypes: deb\nURIs: http://downloadcontent.opensuse.org/repositories/home:/alvistack/xUbuntu_24.04\n" | sudo tee /etc/apt/sources.list.d/home-alvistack.sources > /dev/null
      curl -fsSL https://downloadcontent.opensuse.org/repositories/home:alvistack/xUbuntu_24.04/Release.key | sudo tee /etc/apt/keyrings/home-alvistack.asc > /dev/null
      sudo -E apt-get update
      sudo -E apt-get install -y python3-molecule python3-molecule-plugins
    fi
    sh -x -c "molecule --version"

.script-bootstrap-docker: &script-bootstrap-docker
  - |
    if ! [[ -x "$(command -v docker)" ]]; then
      export DEBIAN_FRONTEND="noninteractive"
      printf "Components:\nEnabled: yes\nX-Repolib-Name: alvistack\nSigned-By: /etc/apt/keyrings/home-alvistack.asc\nSuites: /\nTypes: deb\nURIs: http://downloadcontent.opensuse.org/repositories/home:/alvistack/xUbuntu_24.04\n" | sudo tee /etc/apt/sources.list.d/home-alvistack.sources > /dev/null
      curl -fsSL https://downloadcontent.opensuse.org/repositories/home:alvistack/xUbuntu_24.04/Release.key | sudo tee /etc/apt/keyrings/home-alvistack.asc > /dev/null
      sudo -E apt-get update
      sudo -E apt-get install -y crun podman podman-docker
    fi
    sh -x -c "docker --version"

.script-bootstrap-packer: &script-bootstrap-packer
  - |
    if ! [[ -x "$(command -v packer)" ]]; then
      export DEBIAN_FRONTEND="noninteractive"
      printf "Components:\nEnabled: yes\nX-Repolib-Name: alvistack\nSigned-By: /etc/apt/keyrings/home-alvistack.asc\nSuites: /\nTypes: deb\nURIs: http://downloadcontent.opensuse.org/repositories/home:/alvistack/xUbuntu_24.04\n" | sudo tee /etc/apt/sources.list.d/home-alvistack.sources > /dev/null
      curl -fsSL https://downloadcontent.opensuse.org/repositories/home:alvistack/xUbuntu_24.04/Release.key | sudo tee /etc/apt/keyrings/home-alvistack.asc > /dev/null
      sudo -E apt-get update
      sudo -E apt-get install -y packer packer-plugin-libvirt
    fi
    sh -x -c "packer --version"

.script-packer-build: &script-packer-build
  - |
    echo $DOCKER_HUB_TOKEN | sudo -E docker login --username=$DOCKER_HUB_USERNAME --password-stdin
    cd $CI_PROJECT_DIR/packer/$_IMAGE-$_PROVIDER
    sudo -E packer build packer.json

.script-docker-load: &script-docker-load
  - |
    zcat $CI_PROJECT_DIR/packer/$_IMAGE-$_PROVIDER/output-docker/image.tar.gz | sudo -E docker load
    export _ORG="$CI_PROJECT_NAMESPACE"
    export _ID="$(sudo -E docker images | awk '{ print $3 }' | awk 'NR==2')"
    sudo -E docker tag $_ID $_ORG/$_IMAGE:latest

.script-molecule-test: &script-molecule-test
  - |
    export _MOLECULE_INSTANCE_NAME="$(pwgen -1AB 12)"
    sudo -E molecule test -s $_IMAGE-$_PROVIDER

.script-docker-push: &script-docker-push
  - |
    if [[ -n "$CI_COMMIT_TAG" ]] && [[ "$CI_COMMIT_TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]]; then
      export _TAG="$CI_COMMIT_TAG"
    elif [[ -n "$CI_COMMIT_BRANCH" ]] && [[ "$CI_COMMIT_BRANCH" =~ master ]]; then
      export _TAG="$(date +%Y%m%d).0.0"
    else
      exit 0
    fi
    echo $DOCKER_HUB_TOKEN | sudo -E docker login --username=$DOCKER_HUB_USERNAME --password-stdin
    export _ORG="$CI_PROJECT_NAMESPACE"
    export _ID="$(sudo -E docker images | awk '{ print $3 }' | awk 'NR==2')"
    sudo -E docker tag $_ID $_ORG/$_IMAGE:latest
    sudo -E docker push $_ORG/$_IMAGE:latest
    sudo -E docker tag $_ID $_ORG/$_IMAGE:$_TAG
    sudo -E docker push $_ORG/$_IMAGE:$_TAG

.job-packer-build: &job-packer-build
  script:
    - *script-bootstrap-python
    - *script-bootstrap-ansible
    - *script-bootstrap-docker
    - *script-bootstrap-packer
    - *script-packer-build

.job-molecule-test: &job-molecule-test
  script:
    - *script-bootstrap-python
    - *script-bootstrap-ansible
    - *script-bootstrap-molecule
    - *script-bootstrap-docker
    - *script-docker-load
    - *script-molecule-test

.job-docker-push: &job-docker-push
  script:
    - *script-bootstrap-docker
    - *script-docker-load
    - *script-docker-push

default:
  retry: 2
  before_script:
    - *script-git-submodule
    - *script-linters

build:bamboo-10.2-docker:
  <<: *job-packer-build
  stage: build
  cache:
    key: $CI_PIPELINE_ID-bamboo-10.2-docker
    paths:
      - packer/*/output-docker
  variables:
    _IMAGE: bamboo-10.2
    _PROVIDER: docker

test:bamboo-10.2-docker:
  <<: *job-molecule-test
  stage: test
  cache:
    key: $CI_PIPELINE_ID-bamboo-10.2-docker
    paths:
      - packer/*/output-docker
    policy: pull
  variables:
    _IMAGE: bamboo-10.2
    _PROVIDER: docker
  needs:
    - build:bamboo-10.2-docker

deploy:bamboo-10.2-docker:
  <<: *job-docker-push
  stage: deploy
  cache:
    key: $CI_PIPELINE_ID-bamboo-10.2-docker
    paths:
      - packer/*/output-docker
    policy: pull
  variables:
    _IMAGE: bamboo-10.2
    _PROVIDER: docker
  needs:
    - test:bamboo-10.2-docker

build:bamboo-9.6-docker:
  <<: *job-packer-build
  stage: build
  cache:
    key: $CI_PIPELINE_ID-bamboo-9.6-docker
    paths:
      - packer/*/output-docker
  variables:
    _IMAGE: bamboo-9.6
    _PROVIDER: docker

test:bamboo-9.6-docker:
  <<: *job-molecule-test
  stage: test
  cache:
    key: $CI_PIPELINE_ID-bamboo-9.6-docker
    paths:
      - packer/*/output-docker
    policy: pull
  variables:
    _IMAGE: bamboo-9.6
    _PROVIDER: docker
  needs:
    - build:bamboo-9.6-docker

deploy:bamboo-9.6-docker:
  <<: *job-docker-push
  stage: deploy
  cache:
    key: $CI_PIPELINE_ID-bamboo-9.6-docker
    paths:
      - packer/*/output-docker
    policy: pull
  variables:
    _IMAGE: bamboo-9.6
    _PROVIDER: docker
  needs:
    - test:bamboo-9.6-docker

build:bamboo-9.2-docker:
  <<: *job-packer-build
  stage: build
  cache:
    key: $CI_PIPELINE_ID-bamboo-9.2-docker
    paths:
      - packer/*/output-docker
  variables:
    _IMAGE: bamboo-9.2
    _PROVIDER: docker

test:bamboo-9.2-docker:
  <<: *job-molecule-test
  stage: test
  cache:
    key: $CI_PIPELINE_ID-bamboo-9.2-docker
    paths:
      - packer/*/output-docker
    policy: pull
  variables:
    _IMAGE: bamboo-9.2
    _PROVIDER: docker
  needs:
    - build:bamboo-9.2-docker

deploy:bamboo-9.2-docker:
  <<: *job-docker-push
  stage: deploy
  cache:
    key: $CI_PIPELINE_ID-bamboo-9.2-docker
    paths:
      - packer/*/output-docker
    policy: pull
  variables:
    _IMAGE: bamboo-9.2
    _PROVIDER: docker
  needs:
    - test:bamboo-9.2-docker
