---

os: linux

dist: bionic

language: shell

env:
  jobs:
    - MOLECULE_SCENARIO_NAME="6.10"
    - MOLECULE_SCENARIO_NAME="6.9"

before_install:
  - |
    sudo apt-get -y purge python3-openssl && sudo apt-get -y autoremove
    sudo apt-get update && sudo apt-get install -y ca-certificates curl gcc iproute2 pwgen python3 python3-dev sudo
    curl -skL https://bootstrap.pypa.io/get-pip.py | sudo -H python3
    sudo -H pip3 install --upgrade --ignore-installed --requirement requirements.txt

install:
  - |
    git submodule init
    git submodule sync
    git submodule update

script:
  - |
    source ./scripts/run-tests.sh \
      && sudo -E molecule dependency -s $MOLECULE_SCENARIO_NAME \
      && sudo -E molecule lint -s $MOLECULE_SCENARIO_NAME \
      && sudo -E molecule syntax -s $MOLECULE_SCENARIO_NAME \
      && sudo -E molecule converge -s $MOLECULE_SCENARIO_NAME \
      && sudo -E molecule verify -s $MOLECULE_SCENARIO_NAME

after_success:
  - |
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    export IMAGE=$(docker images | awk '{print $3}' | awk 'NR==2')
    export REPO=$(echo $TRAVIS_REPO_SLUG | sed 's/\/docker-/\//g')
    if [[ -n "$TRAVIS_TAG" ]] && [[ "$TRAVIS_TAG" =~ [^\$MOLECULE_SCENARIO_NAME] ]]; then
      docker tag "$IMAGE" "$REPO":"$TRAVIS_TAG"
      docker push "$REPO":"$TRAVIS_TAG"
      docker tag "$IMAGE" "$REPO":latest
      docker push "$REPO":latest
    elif [[ "$TRAVIS_BRANCH" =~ [^master$] ]]; then
      docker tag "$IMAGE" "$REPO":"$MOLECULE_SCENARIO_NAME"
      docker push "$REPO":"$MOLECULE_SCENARIO_NAME"
    fi
