---

dist: xenial

language: minimal

services: docker

before_install:
  - docker version
  - docker info

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - DOCKER_IMAGE=$(echo $TRAVIS_REPO_SLUG | sed 's/\/docker-/\//g')

script:
  - docker build -t "$DOCKER_IMAGE" .
  - ~/official-images/test/run.sh "$DOCKER_IMAGE"

after_success:
  - |
    if [[ -n "$TRAVIS_TAG" ]]; then
      docker tag "$DOCKER_IMAGE" "$DOCKER_IMAGE":"$TRAVIS_TAG"
      docker push "$DOCKER_IMAGE":"$TRAVIS_TAG"
    elif [[ "$TRAVIS_BRANCH" =~ master ]]; then
      docker tag "$DOCKER_IMAGE" "$DOCKER_IMAGE":latest
      docker push "$DOCKER_IMAGE":latest
    else
      docker tag "$DOCKER_IMAGE" "$DOCKER_IMAGE":"$TRAVIS_BRANCH"
      docker push "$DOCKER_IMAGE":"$TRAVIS_BRANCH"
    fi
