#!/bin/bash

### BEGIN INIT INFO
# Provides:          bamboo
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Initscript for Atlassian Bamboo
# Description:  Automatically start Atlassian Bamboo when the system starts up.
#               Provide commands for manually starting and stopping Bamboo.
### END INIT INFO

BAMBOO_OWNER=${BAMBOO_OWNER:-daemon}
BAMBOO_GROUP=${BAMBOO_GROUP:-daemon}
BAMBOO_HOME=${BAMBOO_HOME:-/var/atlassian/application-data/bamboo}
BAMBOO_CATALINA=${BAMBOO_CATALINA:-/opt/atlassian/bamboo}
BAMBOO_CATALINA_PID=${BAMBOO_CATALINA}/work/catalina.pid

start() {
    echo "Starting Bamboo: "

    mkdir -p ${BAMBOO_HOME}
    chmod -f 755 ${BAMBOO_HOME}
    chown -Rf ${BAMBOO_OWNER}:${BAMBOO_GROUP} ${BAMBOO_HOME}

    if [ "x${USER}" != "x${BAMBOO_OWNER}" ]; then
        su -s /bin/bash ${BAMBOO_OWNER} -c "${BAMBOO_CATALINA}/bin/start-bamboo.sh $@"
    else
        ${BAMBOO_CATALINA}/bin/start-bamboo.sh $@
    fi

    echo "done."
}

stop() {
    echo "Shutting down Bamboo: "

    if [ "x${USER}" != "x${BAMBOO_OWNER}" ]; then
        su -s /bin/bash ${BAMBOO_OWNER} -c "${BAMBOO_CATALINA}/bin/stop-bamboo.sh $@"
    else
        ${BAMBOO_CATALINA}/bin/stop-bamboo.sh $@
    fi

    echo "done."
}

status() {
    if [ -f ${BAMBOO_CATALINA_PID} ]; then
        PID=$(<${BAMBOO_CATALINA_PID})
        if $(kill -0 "${PID:-}" 2> /dev/null); then
            echo "Bamboo is running"
            exit 0
        elif ps "${PID:-}" > /dev/null 2>&1; then
            echo "Bamboo is running"
            exit 0
        else
            echo "Bamboo is not running (pidfile exists)"
            exit 1
        fi
    fi

    echo "Bamboo is not running"

    exit 3
}

case "$1" in
    start)
        shift
        start $@
        ;;
    stop)
        shift
        stop $@
        ;;
    restart)
        shift
        stop $@
        start $@
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac
